// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class Animal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Size { get; set; }
        public string Type { get; set; }
        public int? TrainWagonId { get; set; }
        public int CircusId { get; set; }

        public virtual Circus Circus { get; set; }
        public virtual TrainWagon TrainWagon { get; set; }
    }
}