// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class Circus
    {
        public Circus()
        {
            Animals = new HashSet<Animal>();
        }

        public int Id { get; set; }

        public virtual ICollection<Animal> Animals { get; set; }
    }
}