// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models
{
    public partial class TrainWagon
    {
        public TrainWagon()
        {
            Animals = new HashSet<Animal>();
        }

        public int Id { get; set; }
        public int TrainId { get; set; }
        public int Size { get; set; }

        public virtual Train Train { get; set; }
        public virtual ICollection<Animal> Animals { get; set; }
    }
}